# Generated by Django 6.0.2 on 2026-02-26 10:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usergamestatus_options_follow_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='api_notific_user_id_537f5a_idx',
            old_name='api_notific_user_id_3f21d6_idx',
        ),
    ]
